// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPracownik.Data;

#nullable disable

namespace MvcPracownicy.Migrations
{
    [DbContext(typeof(MvcPracownikContext))]
    partial class MvcPracownikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("MvcStrona.Models.GodzinyNauki", b =>
                {
                    b.Property<int>("IDucznia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Godziny")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jezyk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDucznia");

                    b.ToTable("GodzinyNauki");
                });

            modelBuilder.Entity("MvcStrona.Models.Grupa", b =>
                {
                    b.Property<int>("IDgrupy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jezyk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LiczbaUczestnikow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PracownikIDpracownika")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDgrupy");

                    b.HasIndex("PracownikIDpracownika");

                    b.ToTable("Grupa");
                });

            modelBuilder.Entity("MvcStrona.Models.Pracownik", b =>
                {
                    b.Property<int>("IDpracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Placa")
                        .HasColumnType("TEXT");

                    b.HasKey("IDpracownika");

                    b.ToTable("Pracownik");
                });

            modelBuilder.Entity("MvcStrona.Models.Student", b =>
                {
                    b.Property<int>("IDucznia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDolaczenia")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupaIDgrupy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDucznia");

                    b.HasIndex("GrupaIDgrupy");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MvcStrona.Models.Grupa", b =>
                {
                    b.HasOne("MvcStrona.Models.Pracownik", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PracownikIDpracownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("MvcStrona.Models.Student", b =>
                {
                    b.HasOne("MvcStrona.Models.Grupa", "Grupa")
                        .WithMany()
                        .HasForeignKey("GrupaIDgrupy");

                    b.Navigation("Grupa");
                });
#pragma warning restore 612, 618
        }
    }
}
